name: release
permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: get gleam and otp versions
        id: tool_versions
        shell: bash
        run: |
          export file=$(cat .tool-versions | sed 's/ /=/g')
          for line in $file; do
            echo $line >> $GITHUB_OUTPUT
          done
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1
        with:
          otp-version: ${{ steps.tool_versions.outputs.erlang }}
          gleam-version: ${{ steps.tool_versions.outputs.gleam }}
          rebar3-version: "3"
      - name: Get version from gleam.toml
        id: version
        shell: bash
        run: echo $(grep version gleam.toml | sed 's/ //g' | sed 's/"//g') >> $GITHUB_OUTPUT
      - name: Push tag
        id: tag
        shell: bash
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git tag -a v${{ steps.version.outputs.version }} -m ""
          git push origin v${{ steps.version.outputs.version }} && export pushed_tag=true || export pushed_tag=false

          echo "pushed_tag=$pushed_tag" >> $GITHUB_OUTPUT
      - name: Create Github release
        if: steps.tag.outputs.pushed_tag == 'true'
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3
        with:
          generate_release_notes: true
          make_latest: true
          tag_name: v${{ steps.version.outputs.version }}
      - name: Publish module on hex
        if: steps.tag.outputs.pushed_tag == 'true'
        run: gleam publish --yes
        env:
          HEXPM_USER: ${{ secrets.hex_user }}
          HEXPM_PASS: ${{ secrets.hex_pass }}
