name: release
permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - name: get gleam and otp versions
        id: tool_versions
        shell: bash
        run: |
          export file=$(cat .tool-versions | sed 's/ /=/g')
          for line in $file; do
            echo $line >> $GITHUB_OUTPUT
          done
      - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1
        with:
          otp-version: ${{ steps.tool_versions.outputs.erlang }}
          gleam-version: ${{ steps.tool_versions.outputs.gleam }}
          rebar3-version: "3"
      - name: Get version from gleam.toml
        id: version
        shell: bash
        run: echo $(grep version gleam.toml | sed 's/ //g' | sed 's/"//g') >> $GITHUB_OUTPUT
      - name: Push tag
        id: tag
        shell: bash
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git tag -a v${{ steps.version.outputs.version }} -m ""
          git push origin v${{ steps.version.outputs.version }} && export pushed_tag=true || export pushed_tag=false

          echo "pushed_tag=$pushed_tag" >> $GITHUB_OUTPUT
      - name: Create Github release
        if: steps.tag.outputs.pushed_tag == 'true'
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2
        with:
          generate_release_notes: true
          make_latest: true
          tag_name: v${{ steps.version.outputs.version }}
      - name: Publish module on hex
        if: steps.tag.outputs.pushed_tag == 'true'
        run: gleam publish --yes
        env:
          HEXPM_USER: ${{ secrets.hex_user }}
          HEXPM_PASS: ${{ secrets.hex_pass }}
