name: test
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: get gleam and otp versions
        id: tool_versions
        shell: bash
        run: |
          export file=$(cat .tool-versions | sed 's/ /=/g')
          for line in $file; do
            echo $line >> $GITHUB_OUTPUT
          done
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1
        with:
          otp-version: ${{ steps.tool_versions.outputs.erlang }}
          gleam-version: ${{ steps.tool_versions.outputs.gleam }}
          rebar3-version: "3"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
